+ This notebook is part of lecture 25 *Symmetric matrices and positive definiteness* in the OCW MIT course 18.06 by Prof Gilbert Strang [1]
+ Created by me, Dr Juan H Klopper
    + Head of Acute Care Surgery
    + Groote Schuur Hospital
    + University Cape Town
    + <a href="mailto:juan.klopper@uct.ac.za">Email me with your thoughts, comments, suggestions and corrections</a> 
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Linear Algebra OCW MIT18.06</span> <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">IPython notebook [2] study notes by Dr Juan H Klopper</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

+ [1] <a href="http://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/index.htm">OCW MIT 18.06</a>
+ [2] Fernando Pérez, Brian E. Granger, IPython: A System for Interactive Scientific Computing, Computing in Science and Engineering, vol. 9, no. 3, pp. 21-29, May/June 2007, doi:10.1109/MCSE.2007.53. URL: http://ipython.org

In [1]:
from IPython.core.display import HTML, Image
css_file = 'style.css'
HTML(open(css_file, 'r').read())

In [2]:
from IPython.core.display import HTML, Image
css_file = 'style.css'
HTML(open(css_file, 'r').read())

In [3]:
from sympy import init_printing, Matrix, symbols, sqrt
from warnings import filterwarnings

In [4]:
init_printing(use_latex = 'mathjax')
filterwarnings('ignore')

# Symmetric matrices
# Positive definite matrices

## Symmetric matrices

* Symmetric matrices are square with the following property
$$ {A}={A}^{T} $$

* We are concerned with the eigenvalues and eigenvectors of symmetric matrices
    * The eigenvalues are real
    * The eigenvectors are orthogonal, or at least, can be chosen orthogonal

* Considering proof of the real nature of eigenvalues we have the following
    * Any matrix equation of the following example can be changed to its complex conjugate form by changing each element into its complex conjugate form (here marked with a bar over the top)
    $$ {A}\underline{x}={\lambda}\underline{x} \\ {A}\overline{x}=\overline{\lambda}\overline{x} $$
    * We can take the complex conjugate transpose of **x** on both sides
    $$ \overline{x}^{T}A\underline{x}={\lambda}\overline{x}^{T}\underline{x}\dots\left(1\right) $$
    * In the complex conjugate form this becomes the following
    $$ \overline{x}^{T}{A}^{T}\underline{x}=\overline{x}^{T}{\lambda}\underline{x} $$
    * Now if A is symmetric we use the fact that A=A<sup>T</sup>
    $$ \overline{x}^{T}{A}\underline{x}=\overline{x}^{T}\overline{\lambda}\underline{x}\dots\left(2\right) $$
    * Note how the right-hand sides of (1) and (2) are equal and we therefor have the following
    $$ \lambda\overline{x}^{T}\underline{x}=\overline\lambda\overline{x}^{T}\underline{x} $$
    * This means the following
    $$ \lambda=\overline\lambda $$
    * The only ways that this is possible is if the imaginary part is zero and only real eigenvalues are possible
    * Note also what happens if the complex conjugate of the vector **x** is multiplied by the vector itself
        * Remember that **x**<sup>T</sup>**x** is a form of the dot product (which is the length squared)
        * Any number times its complex conjugate gets rid of the imaginary part

* Consider the following symmetric matrix A

In [5]:
A = Matrix([[5, 2], [2, 3]])
A

⎡5  2⎤
⎢    ⎥
⎣2  3⎦

* Let's see if it really is symmetric by making sure that it is equal to it's transpose

In [6]:
A == A.transpose() # Boolean (true or false) statement

True

In [7]:
S, D = A.diagonalize()

* S, the matrix containing the eigenvectors as it's columns
    * Remember that these eigenvectors are not necessarily the same as those you would get doing these problems by hand
    * When substituting the values for &#955;<sub>i</sub> a singular matrix is created with rows that are simply linear combinations of each other
    * You are free to choose values for the components of the eigenvectors for each eigenvalue (usually choosing the simplest ones)

In [8]:
S

⎡   -2          -2     ⎤
⎢─────────  ───────────⎥
⎢      ___      ___    ⎥
⎢1 + ╲╱ 5   - ╲╱ 5  + 1⎥
⎢                      ⎥
⎣    1           1     ⎦

* D, the matrix containing the values of the eigenvalues down the main diagonal

In [9]:
D

⎡    ___               ⎤
⎢- ╲╱ 5  + 4      0    ⎥
⎢                      ⎥
⎢               ___    ⎥
⎣     0       ╲╱ 5  + 4⎦

* In decomposition, a symmetric matrix results in the following
$$ {A}={S}{\Lambda}{S}^{T} $$
* In this case we have an orthogonal matrix times diagonal matrix times transpose of orthogonal matrix
$$ {A}={Q}{\Lambda}{Q}^{T} $$

In [10]:
A.eigenvals()

⎧    ___           ___       ⎫
⎨- ╲╱ 5  + 4: 1, ╲╱ 5  + 4: 1⎬
⎩                            ⎭

In [11]:
A.eigenvects()

⎡⎛    ___         ⎡⎡   -2    ⎤⎤⎞  ⎛  ___         ⎡⎡    -2     ⎤⎤⎞⎤
⎢⎜- ╲╱ 5  + 4, 1, ⎢⎢─────────⎥⎥⎟, ⎜╲╱ 5  + 4, 1, ⎢⎢───────────⎥⎥⎟⎥
⎢⎜                ⎢⎢      ___⎥⎥⎟  ⎜              ⎢⎢    ___    ⎥⎥⎟⎥
⎢⎜                ⎢⎢1 + ╲╱ 5 ⎥⎥⎟  ⎜              ⎢⎢- ╲╱ 5  + 1⎥⎥⎟⎥
⎢⎜                ⎢⎢         ⎥⎥⎟  ⎜              ⎢⎢           ⎥⎥⎟⎥
⎣⎝                ⎣⎣    1    ⎦⎦⎠  ⎝              ⎣⎣     1     ⎦⎦⎠⎦

* We've seen in our example that, indeed, the eigenvalues are real
* Let's see of the eigenvectors are orthogonal by looking at their dot product

In [12]:
eigenvec_1 = Matrix([-2 / (1 + sqrt(5)), 1])
eigenvec_2 = Matrix([-2 / (1 - sqrt(5)), 1])
eigenvec_1.dot(eigenvec_2)

            4                
───────────────────────── + 1
⎛      ___⎞ ⎛    ___    ⎞    
⎝1 + ╲╱ 5 ⎠⋅⎝- ╲╱ 5  + 1⎠    

* This is certainly zero when simplified

In [13]:
(eigenvec_1.dot(eigenvec_2)).simplify() # Using the simplify() method

0

* We need not use symbolic computing (computer algebra system, CAS)
* Let's look at numerical evaluation using numerical python (numpy)

In [14]:
import numpy as np # Using namespace abbreviations

In [15]:
A = np.matrix([[5, 2], [2, 3]])
A

matrix([[5, 2],
        [2, 3]])

In [16]:
w, v = np.linalg.eig(A) # Calculating the eigenvalues and eigenvectors
# The result of np.linalg.eig() is a tuple, the first being the eigenvalues
# The second being the eigenvectors

In [17]:
w

array([ 6.23606798,  1.76393202])

In [18]:
v

matrix([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]])

In [19]:
# Creating the diagonal matrix manually from the eigenvalues
D = np.matrix([[6.23606798, 0], [0, 1.76393202]])
D

matrix([[ 6.23606798,  0.        ],
        [ 0.        ,  1.76393202]])

In [20]:
# Checking to see if our equation for A holds
v * D * np.matrix.transpose(v)

matrix([[ 5.,  2.],
        [ 2.,  3.]])

## Positive definite matrices (referring to symmetric matrices)

* The properties of positive definite (symmetric) matrices 
    * All eigenvalues are positive
    * All pivots are positive
    * All determinants (actually also all *sub*-determinants) are positive

* The fact that a (square symmetric) matrix A is invertible implies the following
    * The determinant is non-zero (actually larger than zero)
    * The determinant is the product of the eigenvalues
    * The determinant must therefor be larger than zero

* For projection matrices
    * The eigenvalues are either 0 or 1
    * If this projection matrix is positive definite
        * The eigenvalues must all be 1 (since they must be larger than zero)
    * The only matrix that satisfies this property is the identity matrix

* The diagonal matrix D is positive definite
    * This means that for any non-zero vector **x** we have **x**<sup>T</sup>D**x**>0
    * Let's look at a 3-component vector with a 3&#215;3 matrix D

In [21]:
d1, d2, d3, x1, x2, x3 = symbols('d1 d2 d3 x1 x2 x3')

In [22]:
D = Matrix([[d1, 0, 0], [0, d2, 0], [0, 0, d3]])
x_vect = Matrix([x1, x2, x3])
x_vect.transpose(), D, x_vect

⎛[x₁  x₂  x₃], ⎡d₁  0   0 ⎤, ⎡x₁⎤⎞
⎜              ⎢          ⎥  ⎢  ⎥⎟
⎜              ⎢0   d₂  0 ⎥  ⎢x₂⎥⎟
⎜              ⎢          ⎥  ⎢  ⎥⎟
⎝              ⎣0   0   d₃⎦  ⎣x₃⎦⎠

* Indeed we have **x**<sup>T</sup>D**x**>0 since the components if **x** are squared and the eigenvalues are all positive

In [23]:
x_vect.transpose() * D * x_vect

⎡     2        2        2⎤
⎣d₁⋅x₁  + d₂⋅x₂  + d₃⋅x₃ ⎦

* Not all symmetric matrices with a positive determinant are definite positive
* Easy matrices to construct with this property have negative values on the main diagonal
* Note below how the eigenvalues are not all more than zero
* Also note how **x**<sup>T</sup>D**x**&#8815;0
* It is important to note that the *sub*-determinant must also be positive
    * In the example below the *sub*-determinant of 3 is -1

In [24]:
A = Matrix([[3, 1], [1, -1]])
A

⎡3  1 ⎤
⎢     ⎥
⎣1  -1⎦

In [25]:
A == A.transpose()

True

In [26]:
A.det()

-4

In [27]:
A.eigenvals()

⎧      ___         ___       ⎫
⎨1 + ╲╱ 5 : 1, - ╲╱ 5  + 1: 1⎬
⎩                            ⎭

In [28]:
A.eigenvects()

⎡⎛      ___     ⎡⎡    -1     ⎤⎤⎞  ⎛    ___         ⎡⎡   -1    ⎤⎤⎞⎤
⎢⎜1 + ╲╱ 5 , 1, ⎢⎢───────────⎥⎥⎟, ⎜- ╲╱ 5  + 1, 1, ⎢⎢─────────⎥⎥⎟⎥
⎢⎜              ⎢⎢    ___    ⎥⎥⎟  ⎜                ⎢⎢      ___⎥⎥⎟⎥
⎢⎜              ⎢⎢- ╲╱ 5  + 2⎥⎥⎟  ⎜                ⎢⎢2 + ╲╱ 5 ⎥⎥⎟⎥
⎢⎜              ⎢⎢           ⎥⎥⎟  ⎜                ⎢⎢         ⎥⎥⎟⎥
⎣⎝              ⎣⎣     1     ⎦⎦⎠  ⎝                ⎣⎣    1    ⎦⎦⎠⎦

In [29]:
S, D = A.diagonalize()

In [30]:
S

⎡    -1          -1    ⎤
⎢───────────  ─────────⎥
⎢    ___            ___⎥
⎢- ╲╱ 5  + 2  2 + ╲╱ 5 ⎥
⎢                      ⎥
⎣     1           1    ⎦

In [31]:
D

⎡      ___             ⎤
⎢1 + ╲╱ 5        0     ⎥
⎢                      ⎥
⎢               ___    ⎥
⎣    0      - ╲╱ 5  + 1⎦

In [32]:
x_vect = Matrix([x1, x2])
x_vect

⎡x₁⎤
⎢  ⎥
⎣x₂⎦

In [33]:
x_vect.transpose() * D * x_vect

⎡  2 ⎛      ___⎞     2 ⎛    ___    ⎞⎤
⎣x₁ ⋅⎝1 + ╲╱ 5 ⎠ + x₂ ⋅⎝- ╲╱ 5  + 1⎠⎦

* In this example the *sub*-determinant of 1 is -3

In [34]:
A = Matrix([[-3, 1], [1, 1]])
A

⎡-3  1⎤
⎢     ⎥
⎣1   1⎦

In [35]:
A == A.transpose()

True

In [36]:
S, D = A.diagonalize()

In [37]:
x_vect.transpose() * D * x_vect

⎡  2 ⎛       ___⎞     2 ⎛    ___    ⎞⎤
⎣x₁ ⋅⎝-1 + ╲╱ 5 ⎠ + x₂ ⋅⎝- ╲╱ 5  - 1⎠⎦